/**
 * Generates src/skins/embedded.ts with imports for all skin JSON files.
 * Run this before building to include new skins.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const skinsDir = join(import.meta.dir, "..", "skins");
const outputFile = join(import.meta.dir, "..", "src", "skins", "embedded.ts");

const jsonFiles = readdirSync(skinsDir).filter((f) => f.endsWith(".json"));

const imports: string[] = [];
const entries: string[] = [];

for (const file of jsonFiles) {
  const name = file.replace(".json", "");
  const varName = name.replace(/-/g, "_");
  imports.push(`import ${varName}Json from "../../skins/${file}";`);
  entries.push(`  "${name}": ${varName}Json,`);
}

const content = `// Auto-generated by scripts/generate-skins.ts - DO NOT EDIT
${imports.join("\n")}

export const embeddedSkins: Record<string, object> = {
${entries.join("\n")}
};
`;

writeFileSync(outputFile, content);
console.log(`Generated ${outputFile} with ${jsonFiles.length} skin(s): ${jsonFiles.join(", ")}`);
